# Configuration for Github App - https://github.com/dessant/label-actions
#
# Note: Be aware of the edge cases of YAML when writing multiline strings:
#   - https://yaml-multiline.info/
#   - https://github.com/dessant/label-actions/issues/1
pulls:
  actions:
    needs-docs:
      comment: |
        Thanks for your pull request! Before this can be merged, we need the following documentation for your module:

        - [Writing Module Documentation](https://github.com/rapid7/metasploit-framework/wiki/Writing-Module-Documentation)
        - [Template](https://github.com/rapid7/metasploit-framework/blob/master/documentation/modules/module_doc_template.md)
        - [Examples](https://github.com/rapid7/metasploit-framework/tree/master/documentation/modules)

    needs-linting:
      comment: |
        Thanks for your pull request! We currently use Rubocop and msftidy to ensure the quality of our code. This can be ran from the root directory of Metasploit:
        
        ```
        rubocop <directory or file>
        tools/dev/msftidy.rb <directory or file>
        ```
        
        It's also possible to automate some of these changes with the `-a` flag:
        
        ```
        rubocop -a <directory or file>
        ```
        
        After making these changes, push to your branch again once all issues have been resolved.

    needs-unique-branch:
      close: true    
      comment: |
        Thanks for your pull request! We require for all contributed code to come from a **from a unique branch** in your repository before it can be merged.

        Please create a new branch in your fork of framework and resubmit this from that branch.

        If you are using Git on the command line that may look like:

        ```
        # Checkout the master branch
        git checkout master

        # Create a new branch for your feature
        git checkout -b <BRANCH_NAME>

        # Add your new files
        git add modules/my-cool-new-module

        # Commit your changes with a relevant message
        git commit

        # Push your changes to GitHub
        git push origin <BRANCH_NAME>

        # Now browse to the following URL and create your pull request!
        # - https://github.com/rapid7/metasploit-framework/pulls        
        ```

        This helps protect the process, ensure users are aware of commits on the branch being considered for merge, allows
        for a location for more commits to be offered without mingling with other contributor changes and allows contributors
        to make progress while a PR is still being reviewed.

        Please do resubmit from a unique branch, we greatly value your contribution! :tada:

    attic:
      close: true
      comment: >
        Thanks so much for your contribution! We agree this belongs in Framework, but some more work or input is needed to merge it.
        Sometimes that means the implementation isn't quite right and a different approach is necessary. Sometimes it just means that
        we or the contributor doesn't have the time or equipment necessary to test it or fix it up. Please feel free to resubmit if
        you address all of the comments!      

issues:
  actions:
    termux:
      comment: |
        Termux is not officially supported. https://github.com/rapid7/metasploit-framework/issues/11023

        However, Metasploit reportedly does work with Termux.

        Refer to the following for more information:

        * https://wiki.termux.com/wiki/Metasploit_Framework
        * termux/termux-packages/issues/715

    potato:
      close: true
      comment: |
        When creating an issue, please ensure that the default issue template has been updated with the required details.

        Closing this issue. If you believe this issue has been closed in error, please provide any relevant output and logs which may be useful in diagnosing the issue.
